### ISSUE TITLE
Task: Change endpoint to `/api/v1/bootstrap` to `/api/v1/root`

### ISSUE THREAD

**Issue by kairoaraujo** [vmware/repository-service-tuf-api#288]
### What is the task about?

This task is about implementing the support for the RSTUF API for Key Rotation.

Currently, we have the endpoint `/api/v1/bootstrap` for the initial bootstrap, which supports methods `GET` and `POST`.

The method `GET` retrieves if the RSTUF setup has a bootstrap done.
The method `POST` accepts a payload that contains the RSTUF settings and the metadata (Root)

In this task, we aim to rename the endpoint to `/api/v1/root` and keep the existing methods and payload.
We don't change the task to the broker as `bootstrap` for the method `POST`
About the method `GET`we can decide if we need to change.

### Parent feature

- https://github.com/vmware/repository-service-tuf/issues/23

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MVrachev** [comment]
After a discussion with @kairoaraujo we realized that by renaming `/api/v1/bootstrap` to `/api/v1/root` we limit ourselfs on how we can use this API endpoint.
In the future, it's possible that additional information could be added to the payload expected by this API and even today we don't share information exclusively only about root but for `targets` settings as well.
That's we decided this issue is obsolete.
